services:
    monaco-client:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: monaco-client
        restart: always
        networks:
            - monaco-network

networks:
    monaco-network:
        external: true
