services:
    monaco-client:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile.dev
        user: "node"
        volumes:
            - .:/app:cached
        ports:
            - "4200:4200"
        command: /bin/sh -c "while sleep 1000; do :; done"
