services:
    monaco-client:
        image: node:20-alpine
        command: sh -c "npm install && npx ng serve --host 0.0.0.0 --poll 2000"
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - "4200:4200"
