services:
    monaco-client:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile.dev
        user: 'node'
        volumes:
            - .:/app:cached
        ports:
            - '4200:4200'
        command: npx ng serve --host 0.0.0.0 --poll 2000
